const { MongoClient } = require('mongodb');

const uri = process.env.MONGODB_URI || 'mongodb+srv://pink-papaya:c3Nr2vYQZfJJuiFz@pinkpapaya.ohd1bmr.mongodb.net/pink-papaya?appName=pinkpapaya';

const stays = [
  {"title":"Sempre","area":"Aldona, North Goa","bed":"4 Beds","guests":"12 Guests","category":"Villa","collections":["Romantic Luxury Escapes","Expansive Views"],"description":"A 100+ year old Portuguese heritage villa in Aldona, lovingly curated by Pink Papaya Stays. Sempre is where history meets barefoot luxury in the quietest corner of North Goa.","aboutContent":"Built in 1828, Sempre is a living testament to Goa's Portuguese legacy. Nestled in the slow-paced village of Aldona, this four-bedroom heritage home has been thoughtfully restored by Pink Papaya Stays to honour its past while welcoming modern comfort. Sun-dappled verandahs, hand-painted walls, heritage art, and a private pool create a setting unlike any other in Goa.","nearbyPlaces":[{"name":"Aldona Village Market","distance":"5 min walk"},{"name":"Corjuem Fort","distance":"10 min drive"},{"name":"Mapusa Friday Market","distance":"20 min drive"},{"name":"Chapora Fort & Vagator Beach","distance":"30 min drive"}]},
  {"title":"Bougainvillea Suite","area":"Aldona, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"A romantic pool suite tucked within the restored 1828 Sempre villa. The Bougainvillea Suite by Pink Papaya Stays is crafted for couples seeking heritage charm and intimate luxury in North Goa.","aboutContent":"The Bougainvillea Suite is one of the signature rooms within Pink Papaya Stays' crown jewel — the Sempre Villa in Aldona. Designed for couples and solo travellers, this room is a canvas of Goa's colonial past: hand-painted walls, restored furniture, curated art, and direct access to the shared pool and lush villa garden.","nearbyPlaces":[{"name":"Aldona Village","distance":"walking distance"},{"name":"Corjuem Fort","distance":"10 min drive"},{"name":"Anjuna Beach","distance":"25 min drive"}]},
  {"title":"Gulmohar Suite","area":"Aldona, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"A serene heritage room in Goa's most characterful restored villa. The Gulmohar Suite at Sempre is where vintage soul meets quiet indulgence, curated by Pink Papaya Stays.","aboutContent":"Named after the iconic flame tree of Goa, the Gulmohar Suite at Sempre is a serene sanctuary within a 100+ year old Portuguese villa in Aldona.","nearbyPlaces":[{"name":"Aldona Village","distance":"walking distance"},{"name":"Corjuem Fort","distance":"10 min drive"},{"name":"Vagator & Anjuna","distance":"25 min drive"}]},
  {"title":"Magnolia Suite","area":"Aldona, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"Soft, elegant, and deeply restful — the Magnolia Suite at Sempre is Pink Papaya Stays' ode to slow travel and refined heritage living in the heart of North Goa's Aldona village.","aboutContent":"The Magnolia Suite is the newest addition to the storied rooms of Sempre, Pink Papaya Stays' prized 1828 heritage villa in Aldona.","nearbyPlaces":[{"name":"Aldona Village","distance":"walking distance"},{"name":"Siolim","distance":"15 min drive"},{"name":"Anjuna","distance":"25 min drive"}]},
  {"title":"Marigold Suite","area":"Aldona, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes","Expansive Views"],"description":"A sun-drenched balcony suite inside one of Goa's most beloved heritage villas. The Marigold Suite at Sempre by Pink Papaya Stays is ideal for those who love waking up to views, birdsong, and slow mornings.","aboutContent":"The Marigold Suite lives on the upper floor of Sempre, Pink Papaya Stays' century-old Portuguese villa in Aldona. It boasts a private balcony perfect for morning chai.","nearbyPlaces":[{"name":"Aldona Market","distance":"5 min walk"},{"name":"Corjuem Fort","distance":"10 min drive"},{"name":"Morjim Beach","distance":"35 min drive"}]},
  {"title":"The Manor","area":"Assagao, North Goa","bed":"3 Beds","guests":"6 Guests","category":"Villa","collections":["Romantic Luxury Escapes","Expansive Views"],"description":"A luxury villa in the heart of Assagao — Pink Papaya Stays' The Manor delivers 3 bedrooms, a private pool, jacuzzi, and a pool table for the ultimate Goa villa experience.","aboutContent":"Nestled in Assagao — Goa's coolest address, home to the best cafés, art galleries, and boutiques — The Manor is Pink Papaya Stays' flagship luxury villa offering.","nearbyPlaces":[{"name":"Assagao Café Strip","distance":"5 min walk"},{"name":"Anjuna Flea Market","distance":"10 min drive"},{"name":"Vagator & Chapora","distance":"10 min drive"}]},
  {"title":"Villa R&R","area":"Benaulim, South Goa","bed":"3 Beds","guests":"6 Guests","category":"Villa","collections":["Walk to the Beach","Romantic Luxury Escapes"],"description":"Escape to South Goa's quieter coast with Villa R&R, a 3BHK private pool villa by Pink Papaya Stays, minutes from Benaulim, Varca, and Colva Beach.","aboutContent":"South Goa has a different energy — wider sands, fewer crowds, more space to breathe — and Villa R&R captures this perfectly.","nearbyPlaces":[{"name":"Benaulim Beach","distance":"5 min drive"},{"name":"Colva Beach","distance":"10 min drive"},{"name":"Varca Beach","distance":"10 min drive"}]},
  {"title":"Benaulim House","area":"Benaulim, South Goa","bed":"3 Beds","guests":"6 Guests","category":"Villa","collections":["Walk to the Beach"],"description":"A spacious 3BHK just a 5-minute walk from Benaulim Beach — Benaulim House by Pink Papaya Stays is South Goa's most convenient family-friendly getaway.","aboutContent":"Benaulim House is a rare find in South Goa: a generous 3-bedroom property within walking distance of one of Goa's most tranquil beaches.","nearbyPlaces":[{"name":"Benaulim Beach","distance":"5 min walk"},{"name":"Colva Beach","distance":"10 min drive"},{"name":"Margao Market","distance":"15 min drive"}]},
  {"title":"Casa Kai","area":"Candolim, North Goa","bed":"3 Beds","guests":"6+2 Guests","category":"Apartment","collections":[],"description":"A stunning 3BHK duplex penthouse with sweeping views near Candolim — Casa Kai by Pink Papaya Stays brings elevated living (literally) to one of North Goa's most loved areas.","aboutContent":"Casa Kai is Pink Papaya Stays' answer to the question: what if a Goa apartment felt like a penthouse in Ibiza?","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga & Calangute","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"The Fieldhouse","area":"Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":["Expansive Views"],"description":"Two jacuzzis, a panoramic sky-meets-paddy view, and two bedrooms crafted for utter privacy. The Fieldhouse by Pink Papaya Stays is the most distinctive 2BHK stay in North Goa.","aboutContent":"There's nothing quite like The Fieldhouse in Goa's holiday landscape. This signature 2BHK by Pink Papaya Stays sits amid the open paddy fields of North Goa with twin private jacuzzis.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga Beach","distance":"15 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"The Green","area":"Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":[],"description":"A lush 2BHK with a private jacuzzi, balcony, and leafy green outlook. The Green by Pink Papaya Stays is romance and relaxation in perfect proportion, just 10 minutes from Candolim Beach.","aboutContent":"True to its name, The Green wraps you in a canopy of tropical foliage that makes Goa's sunshine filter through leaves rather than beat directly down.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga Beach","distance":"15 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Casa Tinu","area":"Saipem, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"A chic 1BHK with a private jacuzzi in Candolim, Casa Tinu by Pink Papaya Stays is the ultimate couples' retreat, combining luxury amenities with Goa's most sought-after location.","aboutContent":"Casa Tinu is a quietly glamorous 1BHK in the heart of Candolim, designed by Pink Papaya Stays for couples who want it all.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Fort Aguada","distance":"12 min drive"},{"name":"Panjim","distance":"20 min drive"}]},
  {"title":"La Amore","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"Love is in the details at La Amore, a luxury 1BHK with private jacuzzi in Candolim, curated by Pink Papaya Stays for couples seeking romance in the heart of North Goa.","aboutContent":"La Amore lives up to its name in every sense. Pink Papaya Stays has poured romance into every corner of this 1BHK Candolim apartment.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga","distance":"10 min drive"},{"name":"Panjim","distance":"20 min drive"}]},
  {"title":"La Solis","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"La Solis by Pink Papaya Stays — a Candolim apartment with jacuzzi and steam — is a rare Goa stay offering full spa-at-home luxury, just 10 minutes from the beach.","aboutContent":"La Solis is the wellness-forward jewel in Pink Papaya Stays' Candolim collection. What sets it apart is the addition of a private steam.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga","distance":"10 min drive"},{"name":"Panjim","distance":"20 min drive"}]},
  {"title":"Casa de Pacato","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach"],"description":"Wake up, walk to the beach — Casa de Pacato by Pink Papaya Stays is a charming 1BHK in Candolim designed for travellers who want the beach close and the noise far.","aboutContent":"Casa de Pacato — meaning 'calm house' in Portuguese — is exactly that. This 1-bedroom Candolim apartment sits within easy walking distance of Candolim Beach.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5 min walk"},{"name":"Baga","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Casa Remi","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach","Romantic Luxury Escapes"],"description":"A 1BHK with a private garden, 10 minutes' walk from Candolim Beach, Casa Remi by Pink Papaya Stays is Goa living at its most natural and unhurried.","aboutContent":"Casa Remi is the garden apartment that Candolim deserves. Managed by Pink Papaya Stays, this 1BHK comes with a lush private garden.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min walk"},{"name":"Baga Beach","distance":"15 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Candolim Bliss","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach","Expansive Views"],"description":"Verdant views, pool access, and a 10-minute walk to the sea — Candolim Bliss by Pink Papaya Stays is the ideal Goa bolt-hole for couples and solo travellers craving calm and convenience.","aboutContent":"Candolim Bliss is a spacious, view-forward 1BHK retreat managed by Pink Papaya Stays in the heart of Candolim.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min walk"},{"name":"Baga","distance":"10 min drive"},{"name":"Panjim","distance":"20 min drive"}]},
  {"title":"Belle Maison","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach","Romantic Luxury Escapes"],"description":"Beautiful by name, beautiful by nature — Belle Maison by Pink Papaya Stays is an elegantly styled 1BHK in Candolim, walking distance from one of North Goa's finest beaches.","aboutContent":"Belle Maison — French for 'beautiful house' — and Pink Papaya Stays has made sure the name earns its keep.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5-10 min walk"},{"name":"Calangute","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Casa Sukriti","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach","Romantic Luxury Escapes"],"description":"Luxury finishes and a 5-minute walk to the beach — Casa Sukriti by Pink Papaya Stays is Candolim's most refined 1BHK, designed for travellers who believe the details make all the difference.","aboutContent":"Casa Sukriti is the luxury-forward 1BHK in Pink Papaya Stays' Candolim portfolio. Styled with premium finishes — marble textures, quality linen, designer touches.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5 min walk"},{"name":"Baga","distance":"10 min drive"},{"name":"Panjim","distance":"25 min drive"}]},
  {"title":"La Prana","area":"Siolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":[],"description":"An airy 2BHK with a generous terrace and verdant views in Siolim — La Prana by Pink Papaya Stays puts you 10 minutes from the beach in one of North Goa's most charming villages.","aboutContent":"La Prana breathes — quite literally, its name means life force — and this 2BHK in Siolim breathes that energy into your Goa holiday.","nearbyPlaces":[{"name":"Uddo Beach","distance":"10 min drive"},{"name":"Morjim Beach","distance":"15 min drive"},{"name":"Anjuna","distance":"20 min drive"}]},
  {"title":"The Green Window","area":"Siolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Expansive Views"],"description":"A dreamy 1BHK in Siolim with a forest-framed view on one side and a pool view on the other — The Green Window by Pink Papaya Stays is where North Goa's nature lovers come to exhale.","aboutContent":"The Green Window is exactly as it sounds: a window into Goa's lush natural world. This 1-bedroom apartment in Siolim is designed around its extraordinary view.","nearbyPlaces":[{"name":"Uddo Beach","distance":"10 min drive"},{"name":"Morjim Beach","distance":"15 min drive"},{"name":"Vagator","distance":"20 min drive"}]},
  {"title":"Siolim Dairies","area":"Siolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":[],"description":"A stylishly designed 1BHK in the heart of Siolim — Siolim Dairies by Pink Papaya Stays is for creative travellers who want North Goa character with design-forward interiors.","aboutContent":"Siolim Dairies is a love letter to Goa's village aesthetic, reinterpreted with a contemporary eye by Pink Papaya Stays.","nearbyPlaces":[{"name":"Siolim Church","distance":"5 min walk"},{"name":"Uddo Beach","distance":"10 min drive"},{"name":"Morjim","distance":"15 min drive"}]},
  {"title":"Casa Sol","area":"Siolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":[],"description":"Sun-soaked, warm, and full of life — Casa Sol by Pink Papaya Stays is a radiant 1BHK in Siolim for travellers who want North Goa's energy with the quiet of a village stay.","aboutContent":"Casa Sol is aptly named. This 1BHK in Siolim by Pink Papaya Stays seems to capture sunlight at every angle.","nearbyPlaces":[{"name":"Siolim Market","distance":"5 min walk"},{"name":"Uddo Beach","distance":"10 min drive"},{"name":"Morjim Beach","distance":"15 min drive"}]},
  {"title":"Banyan Bliss","area":"North Goa","bed":"1 Bed","guests":"2 Guests","category":"Apartment","collections":[],"description":"In the heart of North Goa, Banyan Bliss by Pink Papaya Stays is a peaceful 1BHK surrounded by the kind of tropical green that makes you forget the world outside.","aboutContent":"Named for the magnificent banyan trees that are synonymous with Goa's village character, Banyan Bliss is a tranquil 1-bedroom retreat managed by Pink Papaya Stays.","nearbyPlaces":[{"name":"Calangute & Candolim","distance":"15 min drive"},{"name":"Anjuna","distance":"15 min drive"},{"name":"Vagator","distance":"15 min drive"}]},
  {"title":"Baga Abode","area":"Baga, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach"],"description":"Two minutes from Baga Beach, Baga Abode by Pink Papaya Stays puts Goa's most vibrant beach town on your doorstep, with stylish modern interiors to come home to.","aboutContent":"Baga is where Goa turns the volume up, and Baga Abode is the ideal home base to enjoy every minute of it.","nearbyPlaces":[{"name":"Baga Beach","distance":"2 min drive"},{"name":"Calangute","distance":"5 min drive"},{"name":"Tito's Lane","distance":"5 min walk"}]},
  {"title":"La Mish","area":"Reis Magos, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":[],"description":"A villa-inspired 2BHK with a private pergola and lush garden in Reis Magos — La Mish by Pink Papaya Stays is the most characterful luxury apartment near Candolim.","aboutContent":"La Mish by Pink Papaya Stays earns its reputation as a 'villa-like' apartment by delivering what most apartments cannot: a private pergola, a lush garden, pool access.","nearbyPlaces":[{"name":"Coco Beach","distance":"5 min drive"},{"name":"Reis Magos Fort","distance":"5 min drive"},{"name":"Candolim Beach","distance":"10 min drive"}]},
  {"title":"Umile Dimora","area":"Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":[],"description":"A spacious and serene 2BHK close to Candolim Beach — Umile Dimora by Pink Papaya Stays is understated elegance in one of Goa's most desirable coastal addresses.","aboutContent":"Umile Dimora (Italian for 'humble home') is a beautifully modest name for a beautifully generous apartment near Candolim Beach.","nearbyPlaces":[{"name":"Coco Beach","distance":"5 min drive"},{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Panjim City Centre","distance":"15 min drive"}]},
  {"title":"Casa Hideaway","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":[],"description":"A tucked-away 1BHK with pool access in Candolim — Casa Hideaway by Pink Papaya Stays is the perfect Goa escape for those who want the coast close and the crowd far.","aboutContent":"Casa Hideaway does what it says: it hides you away from the intensity of Goa's tourist belt while keeping you gloriously close to it.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5-10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"},{"name":"Panjim","distance":"20 min drive"}]},
  {"title":"Ninho de Amor","area":"Reis Magos, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"Portuguese for 'love nest' — Ninho de Amor by Pink Papaya Stays is an elegant 1BHK near Candolim designed exclusively for two, where every detail is set to romance.","aboutContent":"The name says it all. Ninho de Amor — Portuguese for 'love nest' — is Pink Papaya Stays' most romantically intentioned 1BHK near Candolim.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Calangute","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"La Ruhe","area":"Reis Magos, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"A chic 1BHK with a private patio near Candolim — La Ruhe by Pink Papaya Stays is designed for those who understand that the best Goa holidays are ones spent doing very little, very stylishly.","aboutContent":"La Ruhe (German for 'the calm') is a fitting name for this quietly chic 1BHK near Candolim, curated by Pink Papaya Stays.","nearbyPlaces":[{"name":"Coco Beach","distance":"5 min drive"},{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga","distance":"12 min drive"}]},
  {"title":"Juno","area":"Near Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":["Expansive Views"],"description":"Infinity pool, open field views, and two beautifully styled bedrooms near Candolim — Juno by Pink Papaya Stays is the apartment that makes Goa look like a painting.","aboutContent":"Juno is named after the film, and much like its namesake, it has a charm that is a little unexpected, full of personality, and impossible not to remember.","nearbyPlaces":[{"name":"Museum of Goa","distance":"4 min drive"},{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Jigsaw","area":"Near Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":[],"description":"Airy, bright, and beautifully put together — Jigsaw by Pink Papaya Stays is a 2BHK near Candolim where every element fits perfectly for an ideal Goa holiday.","aboutContent":"Jigsaw is precisely what its name suggests: a property where every piece comes together just right.","nearbyPlaces":[{"name":"Coco Beach","distance":"5 min drive"},{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Baga","distance":"10 min drive"}]},
  {"title":"The Blue Door","area":"Near Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":["Expansive Views","Romantic Luxury Escapes"],"description":"Step through The Blue Door into a penthouse with panoramic views near Candolim — Pink Papaya Stays' signature 2BHK for those who want North Goa's scenery on full display.","aboutContent":"The Blue Door is an entrance and a promise. Push through it and you find yourself in one of Pink Papaya Stays' most dramatic offerings: a 2BHK penthouse near Candolim.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"},{"name":"Panjim","distance":"20 min drive"}]},
  {"title":"Le Bohemian","area":"Near Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":["Romantic Luxury Escapes"],"description":"Free-spirited and full of colour — Le Bohemian by Pink Papaya Stays is a vibrant 2BHK near Candolim for travellers who love Goa's creative, anything-goes energy.","aboutContent":"Le Bohemian is Goa's spirit in apartment form. Think rattan and macramé, jewel tones and vintage prints.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Calangute","distance":"10 min drive"},{"name":"Baga","distance":"12 min drive"}]},
  {"title":"Casa Viva","area":"Near Candolim, North Goa","bed":"2 Beds","guests":"4+2 Guests","category":"Apartment","collections":["Expansive Views"],"description":"Nestled deep in tropical greenery near Candolim — Casa Viva by Pink Papaya Stays is a serene 2BHK for those who want Goa's nature as their constant companion.","aboutContent":"Casa Viva is where Goa's natural abundance becomes your daily backdrop. This 2-bedroom apartment by Pink Papaya Stays is nestled within dense, lush greenery.","nearbyPlaces":[{"name":"Candolim Beach","distance":"10 min drive"},{"name":"Calangute","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"The Sage Door","area":"Calangute, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Expansive Views","Walk to the Beach"],"description":"Calangute's most photographed 1BHK — The Sage Door by Pink Papaya Stays combines pool access, lush views, and interiors designed to inspire, near Goa's Queen of Beaches.","aboutContent":"The Sage Door is Pink Papaya Stays' most visual property in Calangute — a 1BHK styled with a calm, green-forward aesthetic.","nearbyPlaces":[{"name":"Calangute Beach","distance":"5 min drive"},{"name":"Baga","distance":"5 min drive"},{"name":"Anjuna Flea Market","distance":"15 min drive"}]},
  {"title":"Vista Verde 002","area":"Calangute, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Expansive Views"],"description":"A view-forward 1BHK in Calangute — Vista Verde 002 by Pink Papaya Stays delivers Goa's best pool-meets-green panorama from one of North Goa's most central locations.","aboutContent":"Vista Verde means 'green view', and the 002 designation marks this as the second in a two-apartment building designed around that very concept.","nearbyPlaces":[{"name":"Calangute Beach","distance":"5 min drive"},{"name":"Baga","distance":"5 min drive"},{"name":"Panjim","distance":"25 min drive"}]},
  {"title":"Casa Siesta","area":"Calangute, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach"],"description":"Near Calangute Beach, styled for rest — Casa Siesta by Pink Papaya Stays is the Goa apartment designed around the art of the afternoon siesta and the beauty of slow days.","aboutContent":"Every great Goa holiday has at least one great siesta — and Casa Siesta by Pink Papaya Stays is built around that truth.","nearbyPlaces":[{"name":"Calangute Beach","distance":"5 min drive"},{"name":"Baga","distance":"5 min drive"},{"name":"Anjuna","distance":"15 min drive"}]},
  {"title":"Belo Nido 003","area":"Calangute, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":[],"description":"A cosy 1BHK with pool access in Calangute — Belo Nido 003 by Pink Papaya Stays is the Portuguese-named 'beautiful nest' that welcomes you into the warmth of North Goa.","aboutContent":"Belo Nido — 'beautiful nest' in Portuguese — is Pink Papaya Stays' cosy offering in Calangute.","nearbyPlaces":[{"name":"Calangute Beach","distance":"5 min drive"},{"name":"Baga","distance":"5 min drive"},{"name":"Candolim","distance":"10 min drive"}]},
  {"title":"Lazy Turtle","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach"],"description":"Five minutes from Candolim Beach, no fuss — Lazy Turtle by Pink Papaya Stays is your budget-smart Goa base that proves a great holiday doesn't require overspending.","aboutContent":"Named in the spirit of Goa itself — unhurried, easygoing, and happily on its own schedule — Lazy Turtle by Pink Papaya Stays is for the traveller who wants to be close to the beach without the luxury price tag.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5 min walk"},{"name":"Baga","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Laziest Turtle","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach"],"description":"Slower than the Lazy Turtle, and proud of it — Laziest Turtle by Pink Papaya Stays is the ultimate no-pressure Goa base, five minutes from Candolim Beach.","aboutContent":"If the Lazy Turtle is laid-back, the Laziest Turtle has fully committed to doing absolutely nothing in a hurry — and guests love it for that energy.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5 min walk"},{"name":"Baga","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
  {"title":"Super Lazy Turtle","area":"Candolim, North Goa","bed":"1 Bed","guests":"2+1 Guests","category":"Apartment","collections":["Walk to the Beach"],"description":"The third in the beloved Turtle trilogy — Super Lazy Turtle by Pink Papaya Stays is five minutes from Candolim Beach and commits fully to the Goa philosophy of taking it easy.","aboutContent":"Three turtles, one philosophy. Super Lazy Turtle is the third in Pink Papaya Stays' beloved Candolim apartment trio.","nearbyPlaces":[{"name":"Candolim Beach","distance":"5 min walk"},{"name":"Baga","distance":"10 min drive"},{"name":"Fort Aguada","distance":"15 min drive"}]},
];

MongoClient.connect(uri).then(async client => {
  const db = client.db('pink-papaya');
  const col = db.collection('stays');

  const existing = await col.find({}, { projection: { title: 1 } }).toArray();
  const existingTitles = new Set(existing.map(s => s.title));

  const toInsert = stays
    .filter(s => !existingTitles.has(s.title))
    .map(s => ({
      ...s,
      id: s.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
      imageUrl: '',
      images: [],
      amenities: [],
      featuredOnHome: false,
      location: s.area,
      faqs: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

  if (toInsert.length === 0) {
    console.log('No new stays to insert — all already exist');
  } else {
    await col.insertMany(toInsert);
    console.log('Inserted:', toInsert.length, 'new stays');
  }

  const total = await col.countDocuments();
  console.log('Total stays in DB:', total);
  await client.close();
}).catch(e => {
  console.error(e.message);
  process.exit(1);
});
